/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shinobu' at '14/11/06 22:44' with Gradle 2.1
 *
 * @author shinobu, @date 14/11/06 22:44
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
